# Default values for kafka-connect-twitter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

## Image Info
## ref: https://hub.docker.com/r/confluentinc/cp-kafka/
image:
  #  repository: jcustenborder/kafka-connect-twitter
  repository: gcr.io/cloud-private-dev/gamussa/kafka-connect-twitter
  tag: 0.2.32

## Specify a imagePullPolicy
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
imagePullPolicy: IfNotPresent

servicePort: 8083

overrideGroupId: "connect-twitter"

## Kafka Connect properties
## ref: https://docs.confluent.io/current/connect/userguide.html#configuring-workers
configurationOverrides:
  "config.storage.topic": "connect-config"
  "config.storage.replication.factor": "2"
  "offset.storage.topic": "connect-offsets"
  "offset.storage.replication.factor": "2"
  "status.storage.topic": "connect-status"
  "status.storage.replication.factor": "2"
  "plugin.path": "/usr/share/java,/usr/share/confluent-hub-components"
  "key.converter": "org.apache.kafka.connect.storage.StringConverter"
  "value.converter": "org.apache.kafka.connect.json.JsonConverter"
  "key.converter.schemas.enable": "false"
  "value.converter.schemas.enable": "false"
  "internal.key.converter": "org.apache.kafka.connect.json.JsonConverter"
  "internal.value.converter": "org.apache.kafka.connect.json.JsonConverter"
  "producer.interceptor.classes": "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
  "producer.confluent.monitoring.interceptor.sasl.mechanism": "SASL_PLAINTEXT"
  # TODO: template it out
  "producer.confluent.monitoring.interceptor.sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"test\" password=\"test123\";"
  "consumer.interceptor.classes": "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
  "consumer.confluent.monitoring.interceptor.sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"test\" password=\"test123\";"
  "consumer.confluent.monitoring.interceptor.security.protocol": "SASL_PLAINTEXT"
  "security.protocol": "SASL_PLAINTEXT"
  "sasl.mechanism": "PLAIN"
  "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"test\" password=\"test123\";"
  "producer.sasl.mechanism": "PLAIN"
  "producer.security.protocol": "SASL_PLAINTEXT"
  "producer.sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"test\" password=\"test123\";"
  "consumer.sasl.mechanism": "PLAIN"
  "consumer.security.protocol": "SASL_PLAINTEXT"
  "consumer.sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"test\" password=\"test123\";"
  "log4j.root.loglevel": "DEBUG"
  "log4j.loggers": "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"

twitter:
  enabled: true
  ## Grab actual values from https://apps.twitter.com
  accessToken: "xxx"
  secret: "xxx"
  key:  "xxx"
  accessTokenSecret: "xxx"
  filterKeywords:
    - apachekafka
    - ksql
    - gamussa
    - kafkastreams
    - kstreams
  kafka:
    topic: "twitter_json_01"
    deleteTopic: "twitter_deletes_json_01"
  maxTasks: 1
  debug: true

## Additional env variables
customEnv: {}

## Monitoring
## Kafka Connect JMX Settings
## ref: https://kafka.apache.org/documentation/#connect_monitoring
jmx:
  port: 5555

## Prometheus Exporter Configuration
## ref: https://prometheus.io/docs/instrumenting/exporters/
prometheus:
  ## JMX Exporter Configuration
  ## ref: https://github.com/prometheus/jmx_exporter
  jmx:
    enabled: true
    image: solsson/kafka-prometheus-jmx-exporter@sha256
    imageTag: 6f82e2b0464f50da8104acd7363fb9b995001ddff77d248379f8788e78946143
    port: 5556

kafka:
  name: kafka
  tls:
    enabled: false
  bootstrapEndpoint: ""

nameOverride: "connect-twitter"
fullnameOverride: "kafka-connect-twitter"

readinessInitialDelay: 20

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
#  cpu: 100m
#  memory: 128Mi
# requests:
#  cpu: 100m
#  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
